name: Go checks
on:
  push:
jobs:
  go-checks:
    # using `main` as the ref will keep your workflow up-to-date
    uses: hashicorp/vault-workflows-common/.github/workflows/go-checks.yaml@main
    secrets:
      VAULT_ECO_GITHUB_TOKEN: ${{ secrets.VAULT_ECO_GITHUB_TOKEN }}
